# This file was generated by GoReleaser. DO NOT EDIT.
cask "context" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "43562d41eaf831b33dd23d1412212a0aae8cadc6bd8b9dce415b0f9eb674e42f"
      url "https://github.com/meesakveld/context/releases/download/v#{version}/context_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b0168e546b3513bddbe2a12bf01d83c7fe73e143b1f1ec4ea1c9e35394cf890a"
      url "https://github.com/meesakveld/context/releases/download/v#{version}/context_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6913703136c1f948c9466aaf1ab975e49217f0d303a00ff2bc204e151051c6a6"
      url "https://github.com/meesakveld/context/releases/download/v#{version}/context_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cccaf5027e3004de174b39b6c2d34ee21f0c13aaf6a6ac66a95ed80af6e23cfd"
      url "https://github.com/meesakveld/context/releases/download/v#{version}/context_linux_amd64.tar.gz"
    end
  end

  name "context"
  desc "CLI for turning codebases into structured, AI-ready context"
  homepage "https://github.com/meesakveld/context"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "context"

  # No zap stanza required
end
